version: '3.4'

services:
  datadogapi:
    image: ${DOCKER_REGISTRY-}datadogapi
    build:
      context: .
      dockerfile: DatadogApi/Dockerfile
networks:
  default:
    name: platform
    external: true
